services:
  app:
    build:
      context: .
    container_name: app
    volumes:
      - ./src:/var/www/html
      - ./supervisor/supervisord.conf:/etc/supervisord.conf
    ports:
      - "9000:9000"
      - "8080:8080"
      - "5173:5173"
    depends_on:
      - mysql
      - redis
    restart: unless-stopped
    command: ["supervisord", "-c", "/etc/supervisord.conf"]
    networks:
      - detpos

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped
    depends_on:
      - mysql
      - app
    networks:
      - detpos

  mysql:
    image: mysql/mysql-server:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:${MYSQL_PORT}"
    restart: unless-stopped
    networks:
      - detpos

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - detpos

  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
      - ./mosquitto/passwd:/mosquitto/config/passwd
    ports:
      - "1884:1883"
      - "9002:9001"
    
  composer:
    image: composer:latest
    container_name: composer
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    command: ["composer"]
    networks:
      - detpos
  
  queue:
    image: php:8.2-fpm-alpine
    container_name: queue
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - mysql
      - redis
    command: ["php", "artisan", "queue:work"]
    networks:
      - detpos

volumes:
  mysql-data:

networks:
  detpos:
    driver: bridge
